apiVersion: batch/v1
kind: Job
metadata:
  namespace: filetracker
  name: e2e-test-app-job
spec:
  template:
    metadata:
      name: e2e-test-app-pod
    spec:
      containers:
        - name: e2e-test-app
          image: fideliswaweu19/cypress-fi
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      restartPolicy: Never
      volumes:
        - name: jenkins-vol
          persistentVolumeClaim: 
            claimName: jenkins-pv-claim  