apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  namespace: filetracker
  labels:
    app: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      name: express-api
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: fideliswaweu19/express-api
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: express-api-service
  namespace: filetracker 
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
