apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-vue-app
  namespace: filetracker 
  labels:
    app: ui-vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-vue-app
  template:
    metadata:
      name: ui-vue-app
      labels:
        app: ui-vue-app
    spec:
      containers:
        - name: ui-vue-app
          image: fideliswaweu19/ui-vue-app
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
