apiVersion: v1
kind: Service
metadata:
  name: ui-vue-app-service
  namespace: filetracker 
spec:
  selector:
    app: ui-vue-app-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort